# Generated by Django 3.2.9 on 2022-03-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistor', '0004_auto_20220228_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='catergory',
            field=models.CharField(choices=[('AS', 'Assignment'), ('DO', 'Document'), ('JO', 'Journal'), ('QU', 'Quiz'), ('SL', 'Slides'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=8192),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=2048)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='assistor.course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DR', 'Dr.'), ('HO', 'Hon.'), ('JR', 'Jr.'), ('MR', 'Mr.'), ('MS', 'Mrs.'), ('MI', 'Ms'), ('PR', 'Prof.'), ('SR', 'Sr.')], default='PR', max_length=2)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True, unique=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='assistor.course')),
            ],
        ),
    ]
